# Generated by Django 6.0.6 on 2026-10-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL do YouTube')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('format_choice', models.CharField(choices=[('mp4', 'MP4'), ('webm', 'WebM'), ('mp3', 'MP3'), ('wav', 'WAV'), ('flac', 'FLAC')], max_length=10, verbose_name='Formato')),
                ('quality', models.CharField(choices=[('1080p', '1080p'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p'), ('320kbps', '320kbps'), ('192kbps', '192kbps'), ('128kbps', '128kbps'), ('64kbps', '64kbps')], max_length=10, verbose_name='Qualidade')),
                ('file', models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='Arquivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo')),
                ('progress', models.IntegerField(default=0, verbose_name='Progresso')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='ytdownloader.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
